# Ansible Playbook for Subutai Hypothesis Blueprint
--- 

- hosts: hypothesis
  remote_user: root
  tasks:

    # -------------------------------------------------------------------------
    # Freshen up the host
    # -------------------------------------------------------------------------

    - name: Disable dpkg fsync
      raw: test -e /etc/dpkg/dpkg.cfg.d/unsafe-io || echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Upgrade packages
      apt:
        update_cache: true
        upgrade: true

    # -------------------------------------------------------------------------
    # Install shit that should be there and fix locales
    # -------------------------------------------------------------------------

    - name: Install setup tools
      apt:
        name: 
          - dirmngr
          - apt-transport-https
          - ca-certificates
          - sudo
          - locales
          - curl

    - name: Transfer locales_setup.sh
      copy: src=locales_setup.sh dest=/root/locales_setup.sh

    - name: Execute locales_setup.sh
      command: bash /root/locales_setup.sh

    # -------------------------------------------------------------------------
    # Install all that's needed
    # -------------------------------------------------------------------------

    - name: Install required debs
      apt:
        name:
          - build-essential
          - git
          - libevent-dev
          - libffi-dev
          - libssl-dev
          - libpq-dev
          - libfontconfig
          - nginx
          - python-dev
          - python-virtualenv
          - python-setuptools
          - python-pip

    # -------------------------------------------------------------------------
    # Collectd Repository and Install
    # -------------------------------------------------------------------------

    - name: Install repository keys for Collectd repo
      apt_key: 
        url: https://pkg.ci.collectd.org/pubkey.asc
        state: present
    
    - name: Add binary repository for NodeSource repo
      apt_repository:
        repo: deb http://pkg.ci.collectd.org/deb xenial collectd-5.6
        update_cache: true
        state: present
    
    - name: Install collectd packages
      apt:
        name: collectd
        state: present

    # -------------------------------------------------------------------------
    # Create hypothesis user, dirs
    # -------------------------------------------------------------------------

    - name: Clone hypothesis repository
      git: 
        repo: https://github.com/hypothesis/h.git
        dest: /var/lib/hypothesis
        clone: yes

    - name: Create hypothesis user
      user:
        name: hypothesis
        password: "{{ subutai.user_variables.password }}"
        state: present
        shell: /bin/bash
        system: no
        createhome: no
        home: /var/lib/hypothesis

    - name: Chmod all of /var/lib/hypothesis
      file:
        dest: /var/lib/hypothesis
        owner: hypothesis
        group: hypothesis
        recurse: yes

    # -------------------------------------------------------------------------
    # Prepare Python based environment, install the stuff
    # -------------------------------------------------------------------------

    - name: Prepare python environment
      command: virtualenv -p /usr/bin/python2.7 --system-site-packages --always-copy /var/lib/hypothesis/env 
      become: yes
      become_user: hypothesis

    - name: Install psycopg2, wheel, uwsgi python packages
      pip:
        name:
          - psycopg2
          - uwsgi
          - wheel
          - tox
          - tox-pip-extensions
        executable: /usr/bin/pip

    # -------------------------------------------------------------------------
    # Install NodeSource NodeJS
    # -------------------------------------------------------------------------

    - name: Install repository keys for NodeSource repo
      apt_key: 
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
    
    - name: Add binary repository for NodeSource repo
      apt_repository:
        repo: deb https://deb.nodesource.com/node_11.x/ xenial main
        update_cache: true
        state: present
    
    - name: Add source repository for NodeSource repo
      apt_repository:
        repo: deb-src https://deb.nodesource.com/node_11.x/ xenial main
        update_cache: true
        state: present
    
    - name: Install nodejs
      apt:
        name: nodejs
        state: present

    - name: Install gulp
      npm:
        name: gulp 
        global: yes

    # -------------------------------------------------------------------------
    # Upload configurations
    # -------------------------------------------------------------------------

    - name: Transfer hypothesis.ini
      copy:
        src: hypothesis.ini
        dest: /var/lib/hypothesis/hypothesis.ini
        owner: hypothesis
        mode: 0644

    - name: Transfer service file
      copy:
        src: hypothesis.service
        dest: /etc/systemd/system/hypothesis.service
    
    # -------------------------------------------------------------------------
    # Setup NGINX
    # -------------------------------------------------------------------------

    - name: Stop the NGINX server
      systemd:
        name: nginx
        state: stopped

    - name: Change user from www-data to hypothesis for nginx
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '^user .*www-data;$'
        line: 'user hypothesis;'
    
    - name: Change owner on all files
      file: 
        dest:
          - /var/log/nginx
          - /var/lib/nginx
          - /var/tmp/nginx
        owner: hypothesis
        group: hypothesis
        recurse: yes

    - name: Add new vhost in nginx-hypothesis.conf
      copy:
        src: nginx-hypothesis.conf
        dest: /etc/nginx/sites-available/hypothesis
        mode: 0644
        owner: root

    - name: Create symbolic link to enable
      file: 
        src: /etc/nginx/sites-available/hypothesis
        dest: /etc/nginx/sites-enabled/hypothesis
        state: link

    - name: Disable default vhost
      file:
        path: /etc/nginx/sites-enabled/hypothesis
        state: absent
    
    - name: Change domainname to target domain
      lineinfile:
        path: /etc/nginx/sites-available/hypothesis
        regexp: '.*server_name .*h.envs.subut.ai$'
        line: "   server_name {{ subutai.user_variables.domain }}"
    
    # -------------------------------------------------------------------------
    # Building Hypothesis
    # -------------------------------------------------------------------------

    - name: Add ENV Parameters
      blockinfile:
        path: /etc/environment
        block: |
          NODE_ENV=production
          PYTHONIOENCODING=utf_8
          APP_URL=http://localhost:5000
          AUTHORITY=localhost
          BROKER_URL=amqp://guest:guest@rabbitmq:5672//
          DATABASE_URL=postgresql://postgres@db0/postgres
          ELASTICSEARCH_URL=http://elasticsearch:9200"
          SECRET_KEY="{{ subutai.user_variables.password }}"
          
    - name: Add PATH Modifications
      blockinfile:
        path: /etc/profile.d/hypothesis.sh
        create: yes
        mode: 0755
        block: |
          PATH=/var/lib/hypothesis/bin:$PATH
          PYTHONPATH=/var/lib/hypothesis:$PYTHONPATH
    
    - name: Build node dependencies
        command: "npm ci --production"
    
    - name: Build h js/css
        command: npm run build

    - name: Start up NGINX
      systemd:
        name: nginx
        state: restarted
