# Ansible Playbook for Subutai Hypothesis Blueprint
--- 

- hosts: hypothesis
  remote_user: root
  tasks:

    # -------------------------------------------------------------------------
    # Freshen up the host
    # -------------------------------------------------------------------------

    - name: Disable dpkg fsync
      raw: test -e /etc/dpkg/dpkg.cfg.d/unsafe-io || echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Upgrade debian
      apt:
        update_cache: true
        upgrade: true

    # -------------------------------------------------------------------------
    # Install shit that should be there and fix locales
    # -------------------------------------------------------------------------

    - name: Install setup tools
      apt:
        name: "{{ item }}"
        allow_unauthenticated: yes
      with_items:
        - dirmngr
        - apt-transport-https
        - ca-certificates
        - sudo
        - locales
        - curl

    - name: Transfer locales_setup.sh
      copy: src=locales_setup.sh dest=/root/locales_setup.sh

    - name: Execute locales_setup.sh
      command: bash /root/locales_setup.sh

    # -------------------------------------------------------------------------
    # Install all that's needed
    # -------------------------------------------------------------------------

    - name: Install required debs
      apt:
        name: "{{ item }}"
        state: present
      with_items: 
        - build-essential
        - git
        - libevent-dev
        - libffi-dev
        - libssl-dev
        - libpq-dev
        - libfontconfig
        - nginx
        - python-dev
        - python-virtualenv
        - python-setuptools
        - python-pip

    # -------------------------------------------------------------------------
    # Collectd Repository and Install
    # -------------------------------------------------------------------------

    - name: Install repository keys for Collectd repo
      apt_key: 
        url: https://pkg.ci.collectd.org/pubkey.asc
        state: present
    
    - name: Add binary repository for NodeSource repo
      apt_repository:
        repo: deb http://pkg.ci.collectd.org/deb xenial collectd-5.6
        update_cache: true
        state: present
    
    - name: Install collectd packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - collectd

    # -------------------------------------------------------------------------
    # Create hypothesis user, dirs
    # -------------------------------------------------------------------------

    - name: Create hypothesis user
      user:
        name: hypothesis
        password: "{{ password }}"
        state: present
        shell: /bin/bash
        system: no
        createhome: yes
        home: /var/lib/hypothesis

    # -------------------------------------------------------------------------
    # Prepare Python based environment, install the stuff
    # -------------------------------------------------------------------------

    - name: Prepare python environment
      command: virtualenv -p /usr/bin/python2.7 --system-site-packages --always-copy /var/lib/hypothesis/env 
      become: yes
      become_user: hypothesis

    - name: Install psycopg2, wheel, uwsgi python packages
      pip:
        name: "{{ item }}"
        executable: /usr/bin/pip
      with_items:
        - psycopg2
        - uwsgi
        - wheel
        - tox
        - tox-pip-extensions

    # -------------------------------------------------------------------------
    # Install NodeSource NodeJS
    # -------------------------------------------------------------------------

    - name: Install repository keys for NodeSource repo
      apt_key: 
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
    
    - name: Add binary repository for NodeSource repo
      apt_repository:
        repo: deb https://deb.nodesource.com/node_11.x/ xenial main
        update_cache: true
        state: present
    
    - name: Add source repository for NodeSource repo
      apt_repository:
        repo: deb-src https://deb.nodesource.com/node_11.x/ xenial main
        update_cache: true
        state: present
    
    - name: Install nodejs
      apt:
        name: nodejs
        state: present

    - name: Install npm
      npm:
        name: "{{ item }}"
        global: yes
      with_items:
        - npm
        - gulp 

    # -------------------------------------------------------------------------
    # Upload configurations
    # -------------------------------------------------------------------------

    - name: Transfer hypothesis.ini
      copy:
        src: hypothesis.ini
        dest: /var/lib/hypothesis/hypothesis.ini
        owner: hypothesis
        mode: 0644

    - name: Transfer service file
      copy:
        src: hypothesis.service
        dest: /etc/systemd/system/hypothesis.service
    
    - name: Clone hypothesis repository
      git: 
        repo: https://github.com/hypothesis/h.git
        dest: /var/lib/hypothesis/repo
        clone: yes
      become: yes
      become_user: hypothesis

    # -------------------------------------------------------------------------
    # Setup NGINX
    # -------------------------------------------------------------------------

    - name: Stop the NGINX server
      systemd:
      name: nginx
      state: stopped

    - name: Change user from www-data to hypothesis for nginx
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '^user .*www-data;$'
        line: 'user hypothesis;'
    
    - name: Change owner on all files
      file: 
        dest: "{{ item }}"
        owner: hypothesis
        group: hypothesis
        recurse: yes
      with_items:
        - /var/log/nginx
        - /var/lib/nginx
        - /var/tmp/nginx

    - name: Add new vhost in nginx-hypothesis.conf
      copy:
        src: nginx-hypothesis.conf
        dest: /etc/nginx/sites-available/hypothesis
        mode: 0644
        owner: root

    - name: Create symbolic link to enable
      file: 
        src: /etc/nginx/sites-available/hypothesis
        dest: /etc/nginx/sites-enabled/hypothesis
        state: link

    - name: Disable default vhost
      file:
        path: /etc/nginx/sites-enabled/hypothesis
        state: absent
    
    - name: Change domainname to target domain
      lineinfile:
        path: /etc/nginx/sites-available/hypothesis
        regexp: '.*server_name .*h.envs.subut.ai$'
        line: "   server_name {{ domain }}"
    
    - name: Start up NGINX
      systemd:
        name: nginx
        state: restarted
